# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='history_id',
        ),
        migrations.AddField(
            model_name='history',
            name='dateCompleted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
