# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161026_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='participant_id',
            new_name='participant',
        ),
    ]
