# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161026_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
    ]
