# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161026_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
    ]
