# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161119_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
    ]
