# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161120_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=main.models.fileUploadPath),
        ),
        migrations.AddField(
            model_name='component',
            name='filetype',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
