# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_component_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='filetype',
            field=models.CharField(default='', max_length=10),
        ),
    ]
