# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_component_filetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='component',
            name='filetype',
        ),
        migrations.AlterField(
            model_name='component',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=main.models.fileUploadPath),
        ),
    ]
